services:

  mysql:
    image: mysql:8.0

    container_name: ems-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 4416
      MYSQL_DATABASE: employee_db

    ports:
      - "3306:3306"

    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p4416"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - ems-network

  backend:
    build:
      image: dpranit/ems-backen:v1

    container_name: ems-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "5001:5001"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - ems-network

  frontend:
    build:
      image: dpranit/ems-frontend:v1

    container_name: ems-frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - ems-network

volumes:
  mysql_data:

networks:
  ems-network:
    driver: bridge
